//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QueueReference.IWebQueue")]
    public interface IWebQueue
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#AvgTimeWait", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.AvgTimeWaitResponse> AvgTimeWaitAsync(QueueReference.AvgTimeWaitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#AvgTimeService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.AvgTimeServiceResponse> AvgTimeServiceAsync(QueueReference.AvgTimeServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#CountWeekDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.CountWeekDayResponse> CountWeekDayAsync(QueueReference.CountWeekDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#PreRegistrInQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.PreRegistrInQueueResponse> PreRegistrInQueueAsync(QueueReference.PreRegistrInQueueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#DelRegistrInQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.DelRegistrInQueueResponse> DelRegistrInQueueAsync(QueueReference.DelRegistrInQueueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#AvgTimeWaitToDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.AvgTimeWaitToDayResponse> AvgTimeWaitToDayAsync(QueueReference.AvgTimeWaitToDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#AvgTimeServiceToDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.AvgTimeServiceToDayResponse> AvgTimeServiceToDayAsync(QueueReference.AvgTimeServiceToDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#GetWorkTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.GetWorkTimeResponse> GetWorkTimeAsync(QueueReference.GetWorkTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#GetAvgTimeHour", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.GetAvgTimeHourResponse> GetAvgTimeHourAsync(QueueReference.GetAvgTimeHourRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#ListAbonInQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.ListAbonInQueueResponse> ListAbonInQueueAsync(QueueReference.ListAbonInQueueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#CountAbonInQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.CountAbonInQueueResponse> CountAbonInQueueAsync(QueueReference.CountAbonInQueueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#ListAbonRedirect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.ListAbonRedirectResponse> ListAbonRedirectAsync(QueueReference.ListAbonRedirectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#ListAbonDelay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.ListAbonDelayResponse> ListAbonDelayAsync(QueueReference.ListAbonDelayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#ListWindow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.ListWindowResponse> ListWindowAsync(QueueReference.ListWindowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#RedirectAbon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.RedirectAbonResponse> RedirectAbonAsync(QueueReference.RedirectAbonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#DelayAbon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.DelayAbonResponse> DelayAbonAsync(QueueReference.DelayAbonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#NextAbonRedirect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.NextAbonRedirectResponse> NextAbonRedirectAsync(QueueReference.NextAbonRedirectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#NextAbonDelay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.NextAbonDelayResponse> NextAbonDelayAsync(QueueReference.NextAbonDelayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#NumAbonOnWindow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.NumAbonOnWindowResponse> NumAbonOnWindowAsync(QueueReference.NumAbonOnWindowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#CountAbon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.CountAbonResponse> CountAbonAsync(QueueReference.CountAbonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#CountAbonVIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.CountAbonVIPResponse> CountAbonVIPAsync(QueueReference.CountAbonVIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#NextAbon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.NextAbonResponse> NextAbonAsync(QueueReference.NextAbonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#NextAbonVIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.NextAbonVIPResponse> NextAbonVIPAsync(QueueReference.NextAbonVIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WebQueueIntf-IWebQueue#FGIS_MDM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<QueueReference.FGIS_MDMResponse> FGIS_MDMAsync(QueueReference.FGIS_MDMRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AvgTimeWait", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class AvgTimeWaitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int mfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string start_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string stop_date;
        
        public AvgTimeWaitRequest()
        {
        }
        
        public AvgTimeWaitRequest(string username, string password, string type_data, int mfc, string start_date, string stop_date)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.mfc = mfc;
            this.start_date = start_date;
            this.stop_date = stop_date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AvgTimeWaitResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class AvgTimeWaitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public AvgTimeWaitResponse()
        {
        }
        
        public AvgTimeWaitResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AvgTimeService", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class AvgTimeServiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int mfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string start_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string stop_date;
        
        public AvgTimeServiceRequest()
        {
        }
        
        public AvgTimeServiceRequest(string username, string password, int mfc, string start_date, string stop_date)
        {
            this.username = username;
            this.password = password;
            this.mfc = mfc;
            this.start_date = start_date;
            this.stop_date = stop_date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AvgTimeServiceResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class AvgTimeServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public AvgTimeServiceResponse()
        {
        }
        
        public AvgTimeServiceResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountWeekDay", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class CountWeekDayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int mfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int step;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string start_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string stop_date;
        
        public CountWeekDayRequest()
        {
        }
        
        public CountWeekDayRequest(string username, string password, int mfc, int step, string start_date, string stop_date)
        {
            this.username = username;
            this.password = password;
            this.mfc = mfc;
            this.step = step;
            this.start_date = start_date;
            this.stop_date = stop_date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountWeekDayResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class CountWeekDayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public CountWeekDayResponse()
        {
        }
        
        public CountWeekDayResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PreRegistrInQueue", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class PreRegistrInQueueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int mfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int usluga_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string FIO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string tData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string tTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string email;
        
        public PreRegistrInQueueRequest()
        {
        }
        
        public PreRegistrInQueueRequest(string username, string password, int mfc, int usluga_id, string type_data, string FIO, string tData, string tTime, string phone, string email)
        {
            this.username = username;
            this.password = password;
            this.mfc = mfc;
            this.usluga_id = usluga_id;
            this.type_data = type_data;
            this.FIO = FIO;
            this.tData = tData;
            this.tTime = tTime;
            this.phone = phone;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PreRegistrInQueueResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class PreRegistrInQueueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public PreRegistrInQueueResponse()
        {
        }
        
        public PreRegistrInQueueResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DelRegistrInQueue", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class DelRegistrInQueueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int mfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string tData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string code;
        
        public DelRegistrInQueueRequest()
        {
        }
        
        public DelRegistrInQueueRequest(string username, string password, int mfc, string type_data, string tData, string code)
        {
            this.username = username;
            this.password = password;
            this.mfc = mfc;
            this.type_data = type_data;
            this.tData = tData;
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DelRegistrInQueueResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class DelRegistrInQueueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public DelRegistrInQueueResponse()
        {
        }
        
        public DelRegistrInQueueResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AvgTimeWaitToDay", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class AvgTimeWaitToDayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int mfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string start_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string stop_date;
        
        public AvgTimeWaitToDayRequest()
        {
        }
        
        public AvgTimeWaitToDayRequest(string username, string password, int mfc, string start_date, string stop_date)
        {
            this.username = username;
            this.password = password;
            this.mfc = mfc;
            this.start_date = start_date;
            this.stop_date = stop_date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AvgTimeWaitToDayResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class AvgTimeWaitToDayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public AvgTimeWaitToDayResponse()
        {
        }
        
        public AvgTimeWaitToDayResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AvgTimeServiceToDay", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class AvgTimeServiceToDayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int mfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string start_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string stop_date;
        
        public AvgTimeServiceToDayRequest()
        {
        }
        
        public AvgTimeServiceToDayRequest(string username, string password, int mfc, string start_date, string stop_date)
        {
            this.username = username;
            this.password = password;
            this.mfc = mfc;
            this.start_date = start_date;
            this.stop_date = stop_date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AvgTimeServiceToDayResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class AvgTimeServiceToDayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public AvgTimeServiceToDayResponse()
        {
        }
        
        public AvgTimeServiceToDayResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkTime", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class GetWorkTimeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int mfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int usluga_id;
        
        public GetWorkTimeRequest()
        {
        }
        
        public GetWorkTimeRequest(string username, string password, string type_data, int mfc, int usluga_id)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.mfc = mfc;
            this.usluga_id = usluga_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkTimeResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class GetWorkTimeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetWorkTimeResponse()
        {
        }
        
        public GetWorkTimeResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAvgTimeHour", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class GetAvgTimeHourRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int mfc;
        
        public GetAvgTimeHourRequest()
        {
        }
        
        public GetAvgTimeHourRequest(string username, string password, string type_data, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAvgTimeHourResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class GetAvgTimeHourResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetAvgTimeHourResponse()
        {
        }
        
        public GetAvgTimeHourResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListAbonInQueue", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class ListAbonInQueueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int mfc;
        
        public ListAbonInQueueRequest()
        {
        }
        
        public ListAbonInQueueRequest(string username, string password, string type_data, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListAbonInQueueResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class ListAbonInQueueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ListAbonInQueueResponse()
        {
        }
        
        public ListAbonInQueueResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountAbonInQueue", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class CountAbonInQueueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int mfc;
        
        public CountAbonInQueueRequest()
        {
        }
        
        public CountAbonInQueueRequest(string username, string password, string type_data, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountAbonInQueueResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class CountAbonInQueueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public CountAbonInQueueResponse()
        {
        }
        
        public CountAbonInQueueResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListAbonRedirect", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class ListAbonRedirectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ip_operator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int mfc;
        
        public ListAbonRedirectRequest()
        {
        }
        
        public ListAbonRedirectRequest(string username, string password, string type_data, string ip_operator, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.ip_operator = ip_operator;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListAbonRedirectResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class ListAbonRedirectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ListAbonRedirectResponse()
        {
        }
        
        public ListAbonRedirectResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListAbonDelay", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class ListAbonDelayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ip_operator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int mfc;
        
        public ListAbonDelayRequest()
        {
        }
        
        public ListAbonDelayRequest(string username, string password, string type_data, string ip_operator, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.ip_operator = ip_operator;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListAbonDelayResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class ListAbonDelayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ListAbonDelayResponse()
        {
        }
        
        public ListAbonDelayResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListWindow", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class ListWindowRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int mfc;
        
        public ListWindowRequest()
        {
        }
        
        public ListWindowRequest(string username, string password, string type_data, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListWindowResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class ListWindowResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ListWindowResponse()
        {
        }
        
        public ListWindowResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RedirectAbon", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class RedirectAbonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string num;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string operator_guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int mfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int window_id;
        
        public RedirectAbonRequest()
        {
        }
        
        public RedirectAbonRequest(string username, string password, string type_data, string num, string operator_guid, int mfc, int window_id)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.num = num;
            this.operator_guid = operator_guid;
            this.mfc = mfc;
            this.window_id = window_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RedirectAbonResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class RedirectAbonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public RedirectAbonResponse()
        {
        }
        
        public RedirectAbonResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DelayAbon", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class DelayAbonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string num;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string operator_guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int mfc;
        
        public DelayAbonRequest()
        {
        }
        
        public DelayAbonRequest(string username, string password, string type_data, string num, string time, string operator_guid, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.num = num;
            this.time = time;
            this.operator_guid = operator_guid;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DelayAbonResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class DelayAbonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public DelayAbonResponse()
        {
        }
        
        public DelayAbonResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NextAbonRedirect", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class NextAbonRedirectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ip_operator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string operator_guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string num;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int mfc;
        
        public NextAbonRedirectRequest()
        {
        }
        
        public NextAbonRedirectRequest(string username, string password, string type_data, string ip_operator, string operator_guid, string num, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.ip_operator = ip_operator;
            this.operator_guid = operator_guid;
            this.num = num;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NextAbonRedirectResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class NextAbonRedirectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public NextAbonRedirectResponse()
        {
        }
        
        public NextAbonRedirectResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NextAbonDelay", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class NextAbonDelayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ip_operator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string operator_guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string num;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int mfc;
        
        public NextAbonDelayRequest()
        {
        }
        
        public NextAbonDelayRequest(string username, string password, string type_data, string ip_operator, string operator_guid, string num, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.ip_operator = ip_operator;
            this.operator_guid = operator_guid;
            this.num = num;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NextAbonDelayResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class NextAbonDelayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public NextAbonDelayResponse()
        {
        }
        
        public NextAbonDelayResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NumAbonOnWindow", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class NumAbonOnWindowRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ip_operator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int mfc;
        
        public NumAbonOnWindowRequest()
        {
        }
        
        public NumAbonOnWindowRequest(string username, string password, string type_data, string ip_operator, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.ip_operator = ip_operator;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NumAbonOnWindowResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class NumAbonOnWindowResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public NumAbonOnWindowResponse()
        {
        }
        
        public NumAbonOnWindowResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountAbon", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class CountAbonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ip_operator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int mfc;
        
        public CountAbonRequest()
        {
        }
        
        public CountAbonRequest(string username, string password, string type_data, string ip_operator, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.ip_operator = ip_operator;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountAbonResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class CountAbonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public CountAbonResponse()
        {
        }
        
        public CountAbonResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountAbonVIP", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class CountAbonVIPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ip_operator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int mfc;
        
        public CountAbonVIPRequest()
        {
        }
        
        public CountAbonVIPRequest(string username, string password, string type_data, string ip_operator, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.ip_operator = ip_operator;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountAbonVIPResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class CountAbonVIPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public CountAbonVIPResponse()
        {
        }
        
        public CountAbonVIPResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NextAbon", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class NextAbonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ip_operator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string operator_guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string num;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int mfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int end_call;
        
        public NextAbonRequest()
        {
        }
        
        public NextAbonRequest(string username, string password, string type_data, string ip_operator, string operator_guid, string num, int mfc, int end_call)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.ip_operator = ip_operator;
            this.operator_guid = operator_guid;
            this.num = num;
            this.mfc = mfc;
            this.end_call = end_call;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NextAbonResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class NextAbonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public NextAbonResponse()
        {
        }
        
        public NextAbonResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NextAbonVIP", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class NextAbonVIPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ip_operator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string operator_guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string num;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int mfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int end_call;
        
        public NextAbonVIPRequest()
        {
        }
        
        public NextAbonVIPRequest(string username, string password, string type_data, string ip_operator, string operator_guid, string num, int mfc, int end_call)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.ip_operator = ip_operator;
            this.operator_guid = operator_guid;
            this.num = num;
            this.mfc = mfc;
            this.end_call = end_call;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NextAbonVIPResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class NextAbonVIPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public NextAbonVIPResponse()
        {
        }
        
        public NextAbonVIPResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FGIS_MDM", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class FGIS_MDMRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string start_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string stop_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int mfc;
        
        public FGIS_MDMRequest()
        {
        }
        
        public FGIS_MDMRequest(string username, string password, string type_data, string start_date, string stop_date, int mfc)
        {
            this.username = username;
            this.password = password;
            this.type_data = type_data;
            this.start_date = start_date;
            this.stop_date = stop_date;
            this.mfc = mfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FGIS_MDMResponse", WrapperNamespace="urn:WebQueueIntf-IWebQueue", IsWrapped=true)]
    public partial class FGIS_MDMResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public FGIS_MDMResponse()
        {
        }
        
        public FGIS_MDMResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IWebQueueChannel : QueueReference.IWebQueue, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WebQueueClient : System.ServiceModel.ClientBase<QueueReference.IWebQueue>, QueueReference.IWebQueue
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebQueueClient() : 
                base(WebQueueClient.GetDefaultBinding(), WebQueueClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IWebQueuePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebQueueClient(EndpointConfiguration endpointConfiguration) : 
                base(WebQueueClient.GetBindingForEndpoint(endpointConfiguration), WebQueueClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebQueueClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebQueueClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebQueueClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebQueueClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebQueueClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.AvgTimeWaitResponse> QueueReference.IWebQueue.AvgTimeWaitAsync(QueueReference.AvgTimeWaitRequest request)
        {
            return base.Channel.AvgTimeWaitAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.AvgTimeWaitResponse> AvgTimeWaitAsync(string username, string password, string type_data, int mfc, string start_date, string stop_date)
        {
            QueueReference.AvgTimeWaitRequest inValue = new QueueReference.AvgTimeWaitRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.mfc = mfc;
            inValue.start_date = start_date;
            inValue.stop_date = stop_date;
            return ((QueueReference.IWebQueue)(this)).AvgTimeWaitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.AvgTimeServiceResponse> QueueReference.IWebQueue.AvgTimeServiceAsync(QueueReference.AvgTimeServiceRequest request)
        {
            return base.Channel.AvgTimeServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.AvgTimeServiceResponse> AvgTimeServiceAsync(string username, string password, int mfc, string start_date, string stop_date)
        {
            QueueReference.AvgTimeServiceRequest inValue = new QueueReference.AvgTimeServiceRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.mfc = mfc;
            inValue.start_date = start_date;
            inValue.stop_date = stop_date;
            return ((QueueReference.IWebQueue)(this)).AvgTimeServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.CountWeekDayResponse> QueueReference.IWebQueue.CountWeekDayAsync(QueueReference.CountWeekDayRequest request)
        {
            return base.Channel.CountWeekDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.CountWeekDayResponse> CountWeekDayAsync(string username, string password, int mfc, int step, string start_date, string stop_date)
        {
            QueueReference.CountWeekDayRequest inValue = new QueueReference.CountWeekDayRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.mfc = mfc;
            inValue.step = step;
            inValue.start_date = start_date;
            inValue.stop_date = stop_date;
            return ((QueueReference.IWebQueue)(this)).CountWeekDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.PreRegistrInQueueResponse> QueueReference.IWebQueue.PreRegistrInQueueAsync(QueueReference.PreRegistrInQueueRequest request)
        {
            return base.Channel.PreRegistrInQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.PreRegistrInQueueResponse> PreRegistrInQueueAsync(string username, string password, int mfc, int usluga_id, string type_data, string FIO, string tData, string tTime, string phone, string email)
        {
            QueueReference.PreRegistrInQueueRequest inValue = new QueueReference.PreRegistrInQueueRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.mfc = mfc;
            inValue.usluga_id = usluga_id;
            inValue.type_data = type_data;
            inValue.FIO = FIO;
            inValue.tData = tData;
            inValue.tTime = tTime;
            inValue.phone = phone;
            inValue.email = email;
            return ((QueueReference.IWebQueue)(this)).PreRegistrInQueueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.DelRegistrInQueueResponse> QueueReference.IWebQueue.DelRegistrInQueueAsync(QueueReference.DelRegistrInQueueRequest request)
        {
            return base.Channel.DelRegistrInQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.DelRegistrInQueueResponse> DelRegistrInQueueAsync(string username, string password, int mfc, string type_data, string tData, string code)
        {
            QueueReference.DelRegistrInQueueRequest inValue = new QueueReference.DelRegistrInQueueRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.mfc = mfc;
            inValue.type_data = type_data;
            inValue.tData = tData;
            inValue.code = code;
            return ((QueueReference.IWebQueue)(this)).DelRegistrInQueueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.AvgTimeWaitToDayResponse> QueueReference.IWebQueue.AvgTimeWaitToDayAsync(QueueReference.AvgTimeWaitToDayRequest request)
        {
            return base.Channel.AvgTimeWaitToDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.AvgTimeWaitToDayResponse> AvgTimeWaitToDayAsync(string username, string password, int mfc, string start_date, string stop_date)
        {
            QueueReference.AvgTimeWaitToDayRequest inValue = new QueueReference.AvgTimeWaitToDayRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.mfc = mfc;
            inValue.start_date = start_date;
            inValue.stop_date = stop_date;
            return ((QueueReference.IWebQueue)(this)).AvgTimeWaitToDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.AvgTimeServiceToDayResponse> QueueReference.IWebQueue.AvgTimeServiceToDayAsync(QueueReference.AvgTimeServiceToDayRequest request)
        {
            return base.Channel.AvgTimeServiceToDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.AvgTimeServiceToDayResponse> AvgTimeServiceToDayAsync(string username, string password, int mfc, string start_date, string stop_date)
        {
            QueueReference.AvgTimeServiceToDayRequest inValue = new QueueReference.AvgTimeServiceToDayRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.mfc = mfc;
            inValue.start_date = start_date;
            inValue.stop_date = stop_date;
            return ((QueueReference.IWebQueue)(this)).AvgTimeServiceToDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.GetWorkTimeResponse> QueueReference.IWebQueue.GetWorkTimeAsync(QueueReference.GetWorkTimeRequest request)
        {
            return base.Channel.GetWorkTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.GetWorkTimeResponse> GetWorkTimeAsync(string username, string password, string type_data, int mfc, int usluga_id)
        {
            QueueReference.GetWorkTimeRequest inValue = new QueueReference.GetWorkTimeRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.mfc = mfc;
            inValue.usluga_id = usluga_id;
            return ((QueueReference.IWebQueue)(this)).GetWorkTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.GetAvgTimeHourResponse> QueueReference.IWebQueue.GetAvgTimeHourAsync(QueueReference.GetAvgTimeHourRequest request)
        {
            return base.Channel.GetAvgTimeHourAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.GetAvgTimeHourResponse> GetAvgTimeHourAsync(string username, string password, string type_data, int mfc)
        {
            QueueReference.GetAvgTimeHourRequest inValue = new QueueReference.GetAvgTimeHourRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).GetAvgTimeHourAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.ListAbonInQueueResponse> QueueReference.IWebQueue.ListAbonInQueueAsync(QueueReference.ListAbonInQueueRequest request)
        {
            return base.Channel.ListAbonInQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.ListAbonInQueueResponse> ListAbonInQueueAsync(string username, string password, string type_data, int mfc)
        {
            QueueReference.ListAbonInQueueRequest inValue = new QueueReference.ListAbonInQueueRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).ListAbonInQueueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.CountAbonInQueueResponse> QueueReference.IWebQueue.CountAbonInQueueAsync(QueueReference.CountAbonInQueueRequest request)
        {
            return base.Channel.CountAbonInQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.CountAbonInQueueResponse> CountAbonInQueueAsync(string username, string password, string type_data, int mfc)
        {
            QueueReference.CountAbonInQueueRequest inValue = new QueueReference.CountAbonInQueueRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).CountAbonInQueueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.ListAbonRedirectResponse> QueueReference.IWebQueue.ListAbonRedirectAsync(QueueReference.ListAbonRedirectRequest request)
        {
            return base.Channel.ListAbonRedirectAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.ListAbonRedirectResponse> ListAbonRedirectAsync(string username, string password, string type_data, string ip_operator, int mfc)
        {
            QueueReference.ListAbonRedirectRequest inValue = new QueueReference.ListAbonRedirectRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.ip_operator = ip_operator;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).ListAbonRedirectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.ListAbonDelayResponse> QueueReference.IWebQueue.ListAbonDelayAsync(QueueReference.ListAbonDelayRequest request)
        {
            return base.Channel.ListAbonDelayAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.ListAbonDelayResponse> ListAbonDelayAsync(string username, string password, string type_data, string ip_operator, int mfc)
        {
            QueueReference.ListAbonDelayRequest inValue = new QueueReference.ListAbonDelayRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.ip_operator = ip_operator;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).ListAbonDelayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.ListWindowResponse> QueueReference.IWebQueue.ListWindowAsync(QueueReference.ListWindowRequest request)
        {
            return base.Channel.ListWindowAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.ListWindowResponse> ListWindowAsync(string username, string password, string type_data, int mfc)
        {
            QueueReference.ListWindowRequest inValue = new QueueReference.ListWindowRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).ListWindowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.RedirectAbonResponse> QueueReference.IWebQueue.RedirectAbonAsync(QueueReference.RedirectAbonRequest request)
        {
            return base.Channel.RedirectAbonAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.RedirectAbonResponse> RedirectAbonAsync(string username, string password, string type_data, string num, string operator_guid, int mfc, int window_id)
        {
            QueueReference.RedirectAbonRequest inValue = new QueueReference.RedirectAbonRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.num = num;
            inValue.operator_guid = operator_guid;
            inValue.mfc = mfc;
            inValue.window_id = window_id;
            return ((QueueReference.IWebQueue)(this)).RedirectAbonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.DelayAbonResponse> QueueReference.IWebQueue.DelayAbonAsync(QueueReference.DelayAbonRequest request)
        {
            return base.Channel.DelayAbonAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.DelayAbonResponse> DelayAbonAsync(string username, string password, string type_data, string num, string time, string operator_guid, int mfc)
        {
            QueueReference.DelayAbonRequest inValue = new QueueReference.DelayAbonRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.num = num;
            inValue.time = time;
            inValue.operator_guid = operator_guid;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).DelayAbonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.NextAbonRedirectResponse> QueueReference.IWebQueue.NextAbonRedirectAsync(QueueReference.NextAbonRedirectRequest request)
        {
            return base.Channel.NextAbonRedirectAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.NextAbonRedirectResponse> NextAbonRedirectAsync(string username, string password, string type_data, string ip_operator, string operator_guid, string num, int mfc)
        {
            QueueReference.NextAbonRedirectRequest inValue = new QueueReference.NextAbonRedirectRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.ip_operator = ip_operator;
            inValue.operator_guid = operator_guid;
            inValue.num = num;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).NextAbonRedirectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.NextAbonDelayResponse> QueueReference.IWebQueue.NextAbonDelayAsync(QueueReference.NextAbonDelayRequest request)
        {
            return base.Channel.NextAbonDelayAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.NextAbonDelayResponse> NextAbonDelayAsync(string username, string password, string type_data, string ip_operator, string operator_guid, string num, int mfc)
        {
            QueueReference.NextAbonDelayRequest inValue = new QueueReference.NextAbonDelayRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.ip_operator = ip_operator;
            inValue.operator_guid = operator_guid;
            inValue.num = num;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).NextAbonDelayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.NumAbonOnWindowResponse> QueueReference.IWebQueue.NumAbonOnWindowAsync(QueueReference.NumAbonOnWindowRequest request)
        {
            return base.Channel.NumAbonOnWindowAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.NumAbonOnWindowResponse> NumAbonOnWindowAsync(string username, string password, string type_data, string ip_operator, int mfc)
        {
            QueueReference.NumAbonOnWindowRequest inValue = new QueueReference.NumAbonOnWindowRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.ip_operator = ip_operator;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).NumAbonOnWindowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.CountAbonResponse> QueueReference.IWebQueue.CountAbonAsync(QueueReference.CountAbonRequest request)
        {
            return base.Channel.CountAbonAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.CountAbonResponse> CountAbonAsync(string username, string password, string type_data, string ip_operator, int mfc)
        {
            QueueReference.CountAbonRequest inValue = new QueueReference.CountAbonRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.ip_operator = ip_operator;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).CountAbonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.CountAbonVIPResponse> QueueReference.IWebQueue.CountAbonVIPAsync(QueueReference.CountAbonVIPRequest request)
        {
            return base.Channel.CountAbonVIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.CountAbonVIPResponse> CountAbonVIPAsync(string username, string password, string type_data, string ip_operator, int mfc)
        {
            QueueReference.CountAbonVIPRequest inValue = new QueueReference.CountAbonVIPRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.ip_operator = ip_operator;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).CountAbonVIPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.NextAbonResponse> QueueReference.IWebQueue.NextAbonAsync(QueueReference.NextAbonRequest request)
        {
            return base.Channel.NextAbonAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.NextAbonResponse> NextAbonAsync(string username, string password, string type_data, string ip_operator, string operator_guid, string num, int mfc, int end_call)
        {
            QueueReference.NextAbonRequest inValue = new QueueReference.NextAbonRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.ip_operator = ip_operator;
            inValue.operator_guid = operator_guid;
            inValue.num = num;
            inValue.mfc = mfc;
            inValue.end_call = end_call;
            return ((QueueReference.IWebQueue)(this)).NextAbonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.NextAbonVIPResponse> QueueReference.IWebQueue.NextAbonVIPAsync(QueueReference.NextAbonVIPRequest request)
        {
            return base.Channel.NextAbonVIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.NextAbonVIPResponse> NextAbonVIPAsync(string username, string password, string type_data, string ip_operator, string operator_guid, string num, int mfc, int end_call)
        {
            QueueReference.NextAbonVIPRequest inValue = new QueueReference.NextAbonVIPRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.ip_operator = ip_operator;
            inValue.operator_guid = operator_guid;
            inValue.num = num;
            inValue.mfc = mfc;
            inValue.end_call = end_call;
            return ((QueueReference.IWebQueue)(this)).NextAbonVIPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueueReference.FGIS_MDMResponse> QueueReference.IWebQueue.FGIS_MDMAsync(QueueReference.FGIS_MDMRequest request)
        {
            return base.Channel.FGIS_MDMAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueueReference.FGIS_MDMResponse> FGIS_MDMAsync(string username, string password, string type_data, string start_date, string stop_date, int mfc)
        {
            QueueReference.FGIS_MDMRequest inValue = new QueueReference.FGIS_MDMRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type_data = type_data;
            inValue.start_date = start_date;
            inValue.stop_date = stop_date;
            inValue.mfc = mfc;
            return ((QueueReference.IWebQueue)(this)).FGIS_MDMAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IWebQueuePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IWebQueuePort))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.34.195/cgi-bin/webqueueserverN.exe/soap/IWebQueue");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WebQueueClient.GetBindingForEndpoint(EndpointConfiguration.IWebQueuePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WebQueueClient.GetEndpointAddress(EndpointConfiguration.IWebQueuePort);
        }
        
        public enum EndpointConfiguration
        {
            
            IWebQueuePort,
        }
    }
}
